spring:
  application:
    name: property-service

  datasource:
    url: jdbc:mysql://localhost:3306/stayease_property_db
    username: root
    password: 2000030757
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8084


services:
  owner:
    url: http://localhost:8083

logging:
  level:
    root: INFO
    com.stayease.property_service: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    feign: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"