server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


resilience4j:

  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - feign.RetryableException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
        ignore-exceptions:
          - java.lang.IllegalArgumentException
          - jakarta.validation.ValidationException

    instances:
      owner-service:
        base-config: default

      user-service:
        base-config: default

  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

        record-exceptions:
          - feign.FeignException
          - java.net.ConnectException
          - java.net.SocketTimeoutException

    instances:
      owner-service:
        base-config: default

      user-service:
        base-config: default

spring:
  application:
    name: property-service

  profiles:
    active: local


  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      registry-fetch-interval-seconds: 30
      service-url:
        defaultZone: http://localhost:8761/eureka/

    instance:
      instance-id: ${spring.application.name}:${server.port}
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 90


feign:
  client:
    config:
      default:
        logger-level: FULL

logging:
  level:
    root: INFO
    com.stayease.property_service: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    com.stayease.property_service.config.OwnerClient: DEBUG
    com.stayease.property_service.config.UserClient: DEBUG
    io.github.resilience4j.retry: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/stayease_property_db
    username: root
    password: 2000030757
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

feign:
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 5000


---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://test-db:3306/stayease_property_db
    username: test_user
    password: test_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

feign:
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 5000

---
spring:
  config:
    activate:
      on-profile: cut

  datasource:
    url: jdbc:mysql://cut-db:3306/stayease_property_db
    username: cut_user
    password: cut_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 8000

---
spring:
  config:
    activate:
      on-profile: ete

  datasource:
    url: jdbc:mysql://ete-db:3306/stayease_property_db
    username: ete_user
    password: ete_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000

---
spring:
  config:
    activate:
      on-profile: drt

  datasource:
    url: jdbc:mysql://drt-db:3306/stayease_property_db
    username: drt_user
    password: drt_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

feign:
  client:
    config:
      default:
        connect-timeout: 7000
        read-timeout: 12000

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://prod-db:3306/stayease_property_db
    username: DBName
    password: DBPwd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

feign:
  client:
    config:
      default:
        connect-timeout: 1000
        read-timeout: 3000
